In [ ]:
# Q.2. Row Echelon Form

In [ ]:
import numpy as np

In [ ]:
import sympy as sp

In [ ]:
np.random.seed(64)
A=np.random.randint(0,10,(5,5))
print(A)

[[4 6 7 6 6]
 [1 4 3 5 0]
 [8 6 8 2 0]
 [1 4 2 6 4]
 [5 0 5 9 6]]


In [ ]:
A[0]=1/4*A[0]
A

array([[1, 1, 1, 1, 1],
       [1, 4, 3, 5, 0],
       [8, 6, 8, 2, 0],
       [1, 4, 2, 6, 4],
       [5, 0, 5, 9, 6]])

In [ ]:
A[1]= A[1] - A[0]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  3,  2,  4, -1],
       [ 8,  6,  8,  2,  0],
       [ 1,  4,  2,  6,  4],
       [ 5,  0,  5,  9,  6]])

In [ ]:
A[2]=A[2] - 8*A[0]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  3,  2,  4, -1],
       [ 0, -2,  0, -6, -8],
       [ 1,  4,  2,  6,  4],
       [ 5,  0,  5,  9,  6]])

In [ ]:
A[3]=A[3] - A[0]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  3,  2,  4, -1],
       [ 0, -2,  0, -6, -8],
       [ 0,  3,  1,  5,  3],
       [ 5,  0,  5,  9,  6]])

In [ ]:
A[4]=A[4] - 5*A[0]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  3,  2,  4, -1],
       [ 0, -2,  0, -6, -8],
       [ 0,  3,  1,  5,  3],
       [ 0, -5,  0,  4,  1]])

In [ ]:
A[1]= 1/3*A[1]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  1,  0,  1,  0],
       [ 0, -2,  0, -6, -8],
       [ 0,  3,  1,  5,  3],
       [ 0, -5,  0,  4,  1]])

In [ ]:
A[2]=A[2]+2*A[1]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  1,  0,  1,  0],
       [ 0,  0,  0, -4, -8],
       [ 0,  3,  1,  5,  3],
       [ 0, -5,  0,  4,  1]])

In [ ]:
A[3]=A[3]-3*A[1]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  1,  0,  1,  0],
       [ 0,  0,  0, -4, -8],
       [ 0,  0,  1,  2,  3],
       [ 0, -5,  0,  4,  1]])

In [ ]:
A[4]=A[4]+5*A[1]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  1,  0,  1,  0],
       [ 0,  0,  0, -4, -8],
       [ 0,  0,  1,  2,  3],
       [ 0,  0,  0,  9,  1]])

In [ ]:
A[2]=A[2]+A[3]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  1,  0,  1,  0],
       [ 0,  0,  1, -2, -5],
       [ 0,  0,  1,  2,  3],
       [ 0,  0,  0,  9,  1]])

In [ ]:
A[3]=A[3]-A[2]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  1,  0,  1,  0],
       [ 0,  0,  1, -2, -5],
       [ 0,  0,  0,  4,  8],
       [ 0,  0,  0,  9,  1]])

In [ ]:
A[3]=1/4*A[3]
A

array([[ 1,  1,  1,  1,  1],
       [ 0,  1,  0,  1,  0],
       [ 0,  0,  1, -2, -5],
       [ 0,  0,  0,  1,  2],
       [ 0,  0,  0,  9,  1]])

In [ ]:
A[4]=A[4]-9*A[3]
A

array([[  1,   1,   1,   1,   1],
       [  0,   1,   0,   1,   0],
       [  0,   0,   1,  -2,  -5],
       [  0,   0,   0,   1,   2],
       [  0,   0,   0,   0, -17]])

In [ ]:
A[4]=1/-17 *A[4]
sp.Matrix(A)

Matrix([
[1, 1, 1,  1,  1],
[0, 1, 0,  1,  0],
[0, 0, 1, -2, -5],
[0, 0, 0,  1,  2],
[0, 0, 0,  0,  1]])