In [ ]:
Q.3. Single Value  Decomposition

In [ ]:
import numpy as np
import sympy as sp

In [ ]:
np.random.seed(64)
A=np.random.randint(0,10,(5,5))
sp.Matrix(A)

Matrix([
[4, 6, 7, 6, 6],
[1, 4, 3, 5, 0],
[8, 6, 8, 2, 0],
[1, 4, 2, 6, 4],
[5, 0, 5, 9, 6]])

In [ ]:
A=np.array([[4 ,6 ,7 ,6 ,6],[1 ,4 ,3, 5 ,0],[8 ,6 ,8, 2, 0],[1 ,4 ,2, 6, 4],[5, 0 ,5 ,9 ,6]])
sp.Matrix(A)

Matrix([
[4, 6, 7, 6, 6],
[1, 4, 3, 5, 0],
[8, 6, 8, 2, 0],
[1, 4, 2, 6, 4],
[5, 0, 5, 9, 6]])

In [ ]:
U,S,Vt=np.linalg.svd(A)
print(np.round(U))

[[-1. -0. -0. -1. -0.]
 [-0.  0. -0.  1. -0.]
 [-0.  1.  0.  0.  0.]
 [-0. -0. -0. -0.  1.]
 [-1. -1.  1.  0. -0.]]


In [ ]:
S

array([22.70792894,  8.82420295,  5.18004242,  3.24254367,  1.06605662])

In [ ]:

Sigma=np.zeros((A.shape[0],A.shape[1]))
sp.Matrix(Sigma)

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [ ]:
Sigma[:A.shape[1],:A.shape[0]]=np.diag(S)
sp.Matrix(Sigma)

Matrix([
[22.7079289369021,                0,               0,                0,                0],
[               0, 8.82420295475026,               0,                0,                0],
[               0,                0, 5.1800424182027,                0,                0],
[               0,                0,               0, 3.24254366914427,                0],
[               0,                0,               0,                0, 1.06605661636486]])

In [ ]:
sp.Matrix(Vt)

Matrix([
[-0.407530087397064, -0.383681763606321,  -0.521610458629613, -0.544001237228347, -0.344518091664743],
[ 0.385528508751382,  0.386316239537159,   0.344559721891636,  -0.56884751037599, -0.509724082223707],
[ 0.589934961273294, -0.776452667355229,   0.165051173805528, -0.112965804269557, 0.0953668386577683],
[0.0833951456927645, -0.137812878065761, -0.0841817404730866,  0.605923994643174,  -0.77448202535675],
[ 0.574725141218336,   0.28579176570012,  -0.758203582222151, 0.0238747484689506,  0.112122268085391]])

In [ ]:
#Verifiaction of SVD

In [ ]:
sp.Matrix(np.round(U@Sigma@Vt))

Matrix([
[4.0, 6.0, 7.0, 6.0, 6.0],
[1.0, 4.0, 3.0, 5.0,   0],
[8.0, 6.0, 8.0, 2.0,   0],
[1.0, 4.0, 2.0, 6.0, 4.0],
[5.0,   0, 5.0, 9.0, 6.0]])